In [1]:
!pip install settrade-v2

Requirement already satisfied: settrade-v2 in /opt/anaconda3/lib/python3.13/site-packages (2.2.1)
Requirement already satisfied: requests>=2.27 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (2.32.3)
Requirement already satisfied: cryptography>=37.0 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (44.0.1)
Requirement already satisfied: betterproto>=1.2 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.2.5)
Requirement already satisfied: paho-mqtt<2,>=1.6 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.6.1)
Requirement already satisfied: ntplib>=0.4 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (0.4.0)
Requirement already satisfied: typing-extensions>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (4.12.2)
Requirement already satisfied: grpclib in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (0.4.9)
Requirement already satisfied: stringcase in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (1.2.0)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=37.0->settrade-v2) (1.17.1)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12->cryptography>=37.0->settrade-v2) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2025.8.3)
Requirement already satisfied: h2<5,>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (4.3.0)
Requirement already satisfied: multidict in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (6.1.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (4.1.0)

In [6]:
#import และตั้งค่า Credential
from settrade_v2 import Investor
from pprint import pprint

In [7]:
from settrade_v2 import Investor

APP_ID = "BDYsxwFdwr4CGrqn"
APP_SECRET = "c/YrEWTsD6i7kfib8tF022qBrvNoNKh0jnUsqBtCurQ="
BROKER_ID = "SANDBOX"
APP_CODE = "SANDBOX"

investor = Investor(
    app_id=APP_ID,
    app_secret=APP_SECRET,
    broker_id=BROKER_ID,
    app_code=APP_CODE,
    is_auto_queue=False
)

print("API Connected")

API Connected

In [8]:
market = investor.MarketData()

In [9]:
import pandas as pd
from sqlalchemy import create_engine, text

In [13]:
import pandas as pd

symbols_df = pd.DataFrame({
    "symbol": [
        
    ]
})

# แปลงเป็น list
symbols = symbols_df["symbol"].tolist()

In [14]:
symbols

[]

In [16]:
symbols = ["CRD","CREDIT","CSC","CSP","CSR","CSS","CTARAF","CTW","CV","CWT","D","DCC","DCON","DDD",
        "DELTA","DEMCO","DEXON","DHOUSE","DIF","DIMET","DITTO","DMT","DOD","DOHOME","DPAINT",
        "DREIT","DRT","DTCENT","DTCI","DUSIT","DV8","EA","EASON","EAST","EASTW","ECF","EFORL",
        "EGATIF","EGCO","EKH","EMC","EMPIRE","EP","EPG","ERW","ESTAR","ETC","ETE","ETL","EURO",
        "EVER","F&D","FANCY","FE","FLOYD","FM","FMT","FN","FNS","FORTH","FPI","FPT","FSMART",
        "FSX","FTE","FTI","FTREIT","FUTURERT","FVC","GABLE","GAHREIT","GBX","GC","GCAP","GEL",
        "GENCO","GFC","GFPT","GGC","GJS","GLAND","GLOBAL","GLORY","GPI","GPSC","GRAMMY","GRAND",
        "GREEN","GROREIT","GSTEEL","GTB","GTV","GULF","GUNKUL","GVREIT","GYT","HANA","HANN",
        "HARN","HEALTH","HENG","HFT","HL","HMPRO","HPF","HPT","HTC","HTECH","HUMAN","HYDRO",
        "HYDROGEN","I2","ICC","ICHI","ICN","IDG","IFS","IHL","IIG","III","ILINK","ILM","IMH",
        "IMPACT","IND","INET","INETREIT","INGRS","INOX","INSET","INSURE","IP","IRC","IRCP",
        "IROYAL","IRPC","ISSARA","IT","ITC","ITD","ITEL","ITNS","ITTHI","IVF","IVL","J","JAK",
        "JAS","JCK","JCT","JDF","JMART","JMT","JPARK","JR","JSP","JTS","JUBILE","K","KAMART",
        "KASET","KBANK","KBS","KBSPIF","KC","KCAR","KCC","KCE","KCG","KCM","KDH","KGEN","KGI",
        "KIAT","KISS","KJL","KK","KKC","KKP","KLINIQ","KOOL","KPNREIT","KSL","KTB","KTBSTMR",
        "KTC","KTIS","KTMS","KUMWEL","KUN","KWC","KWI","KWM","KYE","L&E","LALIN","LANNA",
        "LDC","LEE","LEO"]

all_data = []

for symbol in symbols:
    print(f"กำลังดึง {symbol}")
    data = market.get_candlestick(
        symbol=symbol,
        interval="1d",
        limit=260
    )
    df = pd.DataFrame(data)
    df["symbol"] = symbol
    all_data.append(df)

final_df = pd.concat(all_data)
final_df

กำลังดึง CRD
กำลังดึง CREDIT
กำลังดึง CSC
กำลังดึง CSP
กำลังดึง CSR
กำลังดึง CSS
กำลังดึง CTARAF
กำลังดึง CTW
กำลังดึง CV
กำลังดึง CWT
กำลังดึง D
กำลังดึง DCC
กำลังดึง DCON
กำลังดึง DDD
กำลังดึง DELTA
กำลังดึง DEMCO
กำลังดึง DEXON
กำลังดึง DHOUSE
กำลังดึง DIF
กำลังดึง DIMET
กำลังดึง DITTO
กำลังดึง DMT
กำลังดึง DOD
กำลังดึง DOHOME
กำลังดึง DPAINT
กำลังดึง DREIT
กำลังดึง DRT
กำลังดึง DTCENT
กำลังดึง DTCI
กำลังดึง DUSIT
กำลังดึง DV8
กำลังดึง EA
กำลังดึง EASON
กำลังดึง EAST
กำลังดึง EASTW
กำลังดึง ECF
กำลังดึง EFORL
กำลังดึง EGATIF
กำลังดึง EGCO
กำลังดึง EKH
กำลังดึง EMC
กำลังดึง EMPIRE
กำลังดึง EP
กำลังดึง EPG
กำลังดึง ERW
กำลังดึง ESTAR
กำลังดึง ETC
กำลังดึง ETE
กำลังดึง ETL
กำลังดึง EURO
กำลังดึง EVER
กำลังดึง F&D
กำลังดึง FANCY
กำลังดึง FE
กำลังดึง FLOYD
กำลังดึง FM
กำลังดึง FMT
กำลังดึง FN
กำลังดึง FNS
กำลังดึง FORTH
กำลังดึง FPI
กำลังดึง FPT
กำลังดึง FSMART
กำลังดึง FSX
กำลังดึง FTE
กำลังดึง FTI
กำลังดึง FTREIT
กำลังดึง FUTURERT
กำลังดึง FVC
กำลังดึง GABLE
กำลังดึง GAHREIT
กำลังดึง GBX
กำลังดึง GC
กำลังดึง GCAP
กำลังดึง GEL
กำลังดึง GENCO
กำลังดึง GFC
กำลังดึง GFPT
กำลังดึง GGC
กำลังดึง GJS
กำลังดึง GLAND
กำลังดึง GLOBAL
กำลังดึง GLORY
กำลังดึง GPI
กำลังดึง GPSC
กำลังดึง GRAMMY
กำลังดึง GRAND
กำลังดึง GREEN
กำลังดึง GROREIT
กำลังดึง GSTEEL
กำลังดึง GTB
กำลังดึง GTV
กำลังดึง GULF
กำลังดึง GUNKUL
กำลังดึง GVREIT
กำลังดึง GYT
กำลังดึง HANA
กำลังดึง HANN
กำลังดึง HARN
กำลังดึง HEALTH
กำลังดึง HENG
กำลังดึง HFT
กำลังดึง HL
กำลังดึง HMPRO
กำลังดึง HPF
กำลังดึง HPT
กำลังดึง HTC
กำลังดึง HTECH
กำลังดึง HUMAN
กำลังดึง HYDRO
กำลังดึง HYDROGEN
กำลังดึง I2
กำลังดึง ICC
กำลังดึง ICHI
กำลังดึง ICN
กำลังดึง IDG
กำลังดึง IFS
กำลังดึง IHL
กำลังดึง IIG
กำลังดึง III
กำลังดึง ILINK
กำลังดึง ILM
กำลังดึง IMH
กำลังดึง IMPACT
กำลังดึง IND
กำลังดึง INET
กำลังดึง INETREIT
กำลังดึง INGRS
กำลังดึง INOX
กำลังดึง INSET
กำลังดึง INSURE
กำลังดึง IP
กำลังดึง IRC
กำลังดึง IRCP
กำลังดึง IROYAL
กำลังดึง IRPC
กำลังดึง ISSARA
กำลังดึง IT
กำลังดึง ITC
กำลังดึง ITD
กำลังดึง ITEL
กำลังดึง ITNS
กำลังดึง ITTHI
กำลังดึง IVF
กำลังดึง IVL
กำลังดึง J
กำลังดึง JAK
กำลังดึง JAS
กำลังดึง JCK
กำลังดึง JCT
กำลังดึง JDF
กำลังดึง JMART
กำลังดึง JMT
กำลังดึง JPARK
กำลังดึง JR
กำลังดึง JSP
กำลังดึง JTS
กำลังดึง JUBILE
กำลังดึง K
กำลังดึง KAMART
กำลังดึง KASET
กำลังดึง KBANK
กำลังดึง KBS
กำลังดึง KBSPIF
กำลังดึง KC
กำลังดึง KCAR
กำลังดึง KCC
กำลังดึง KCE
กำลังดึง KCG
กำลังดึง KCM
กำลังดึง KDH
กำลังดึง KGEN
กำลังดึง KGI
กำลังดึง KIAT
กำลังดึง KISS
กำลังดึง KJL
กำลังดึง KK
กำลังดึง KKC
กำลังดึง KKP
กำลังดึง KLINIQ
กำลังดึง KOOL
กำลังดึง KPNREIT
กำลังดึง KSL
กำลังดึง KTB
กำลังดึง KTBSTMR
กำลังดึง KTC
กำลังดึง KTIS
กำลังดึง KTMS
กำลังดึง KUMWEL
กำลังดึง KUN
กำลังดึง KWC
กำลังดึง KWI
กำลังดึง KWM
กำลังดึง KYE
กำลังดึง L&E
กำลังดึง LALIN
กำลังดึง LANNA
กำลังดึง LDC
กำลังดึง LEE
กำลังดึง LEO

,lastSequence,time,open,high,low,close,volume,value,symbol
0,0,1.740503e+09,0.36,0.37,0.34,0.35,2575900.0,0.0,CRD
1,0,1.740589e+09,0.34,0.35,0.34,0.35,112401.0,0.0,CRD
2,0,1.740676e+09,0.34,0.35,0.34,0.34,310400.0,0.0,CRD
3,0,1.740935e+09,0.35,0.35,0.34,0.34,166200.0,0.0,CRD
4,0,1.741021e+09,0.34,0.34,0.33,0.34,115600.0,0.0,CRD
...,...,...,...,...,...,...,...,...,...
255,0,1.774458e+09,1.79,1.79,1.75,1.79,38250.0,0.0,LEO
256,0,1.774544e+09,1.76,1.80,1.75,1.79,130755.0,0.0,LEO
257,0,1.774976e+09,1.76,1.81,1.76,1.79,262801.0,0.0,LEO
258,0,1.775063e+09,1.80,1.80,1.77,1.78,119500.0,0.0,LEO
259,0,1.775149e+09,1.77,1.79,1.77,1.77,73700.0,0.0,LEO

In [17]:
import pandas as pd

final_df['time'] = pd.to_datetime(final_df['time'], unit='s')

In [18]:
final_df['symbol'].value_counts()

symbol
CRD        260
CREDIT     260
CSC        260
CSP        260
CSR        260
          ...
KKC        236
FE         213
KPNREIT    170
HANN       157
IDG        108
Name: count, Length: 199, dtype: int64

In [19]:
final_df.head()
final_df.tail()

,lastSequence,time,open,high,low,close,volume,value,symbol
255,0,2026-03-25 17:00:00,1.79,1.79,1.75,1.79,38250.0,0.0,LEO
256,0,2026-03-26 17:00:00,1.76,1.80,1.75,1.79,130755.0,0.0,LEO
257,0,2026-03-31 17:00:00,1.76,1.81,1.76,1.79,262801.0,0.0,LEO
258,0,2026-04-01 17:00:00,1.80,1.80,1.77,1.78,119500.0,0.0,LEO
259,0,2026-04-02 17:00:00,1.77,1.79,1.77,1.77,73700.0,0.0,LEO

In [20]:
import pandas as pd

# แปลง Unix timestamp → datetime
final_df["date"] = pd.to_datetime(final_df["time"], unit="s")

# เรียงข้อมูลตาม หุ้น + วันที่
final_df = final_df.sort_values(["symbol", "date"])

final_df.head()

,lastSequence,time,open,high,low,close,volume,value,symbol,date
0,0,2025-02-25 17:00:00,0.36,0.37,0.34,0.35,2575900.0,0.0,CRD,2025-02-25 17:00:00
1,0,2025-02-26 17:00:00,0.34,0.35,0.34,0.35,112401.0,0.0,CRD,2025-02-26 17:00:00
2,0,2025-02-27 17:00:00,0.34,0.35,0.34,0.34,310400.0,0.0,CRD,2025-02-27 17:00:00
3,0,2025-03-02 17:00:00,0.35,0.35,0.34,0.34,166200.0,0.0,CRD,2025-03-02 17:00:00
4,0,2025-03-03 17:00:00,0.34,0.34,0.33,0.34,115600.0,0.0,CRD,2025-03-03 17:00:00

In [22]:
final_df.groupby("symbol")["date"].agg(["min", "max"])

                       min                 max
symbol
CRD    2025-02-25 17:00:00 2026-04-02 17:00:00
CREDIT 2025-03-05 17:00:00 2026-04-02 17:00:00
CSC    2025-02-10 17:00:00 2026-04-02 17:00:00
CSP    2025-03-04 17:00:00 2026-04-02 17:00:00
CSR    2023-08-31 17:00:00 2026-04-02 17:00:00
...                    ...                 ...
LALIN  2025-03-05 17:00:00 2026-04-02 17:00:00
LANNA  2025-03-05 17:00:00 2026-04-02 17:00:00
LDC    2025-03-05 17:00:00 2026-04-02 17:00:00
LEE    2025-03-03 17:00:00 2026-04-02 17:00:00
LEO    2025-03-05 17:00:00 2026-04-02 17:00:00

[199 rows x 2 columns]

In [23]:
import pandas as pd
from sqlalchemy import create_engine

In [24]:
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/thai_stock_market"
)

print("Connected to thai_stock_market")

Connected to thai_stock_market

In [25]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

tables_df = pd.read_sql(query, engine)
tables_df

   table_name
0  categories
1      stocks
2      prices

In [26]:
stocks_schema = pd.read_sql("""
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'stocks';
""", engine)

stocks_schema

   column_name          data_type
0    div_yield            numeric
1          eps            numeric
2     stock_id            integer
3  category_id            integer
4           pe            numeric
5          pbv            numeric
6       symbol  character varying
7   stock_name               text

In [27]:
prices_schema = pd.read_sql("""
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'prices';
""", engine)

prices_schema

  column_name data_type
0    price_id   integer
1    stock_id   integer
2  trade_date      date
3        open   numeric
4        high   numeric
5         low   numeric
6       close   numeric
7      volume    bigint
8  market_cap   numeric

In [28]:
pd.read_sql("SELECT COUNT(*) FROM stocks;", engine)

   count
0    198

In [29]:
pd.read_sql("SELECT COUNT(*) FROM prices;", engine)

    count
0  101322

In [30]:
symbols_df = (
    final_df[['symbol']]
    .drop_duplicates()
    .reset_index(drop=True)
)

symbols_df

     symbol
0       CRD
1    CREDIT
2       CSC
3       CSP
4       CSR
..      ...
194   LALIN
195   LANNA
196     LDC
197     LEE
198     LEO

[199 rows x 1 columns]

In [31]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/thai_stock_market"
)

print("DB Connected")

DB Connected

In [55]:
symbols = ["CRD","CREDIT","CSC","CSP","CSR","CSS","CTARAF","CTW","CV","CWT","D","DCC","DCON","DDD",
        "DELTA","DEMCO","DEXON","DHOUSE","DIF","DIMET","DITTO","DMT","DOD","DOHOME","DPAINT",
        "DREIT","DRT","DTCENT","DTCI","DUSIT","DV8","EA","EASON","EAST","EASTW","ECF","EFORL",
        "EGATIF","EGCO","EKH","EMC","EMPIRE","EP","EPG","ERW","ESTAR","ETC","ETE","ETL","EURO",
        "EVER","F&D","FANCY","FE","FLOYD","FM","FMT","FN","FNS","FORTH","FPI","FPT","FSMART",
        "FSX","FTE","FTI","FTREIT","FUTURERT","FVC","GABLE","GAHREIT","GBX","GC","GCAP","GEL",
        "GENCO","GFC","GFPT","GGC","GJS","GLAND","GLOBAL","GLORY","GPI","GPSC","GRAMMY","GRAND",
        "GREEN","GROREIT","GSTEEL","GTB","GTV","GULF","GUNKUL","GVREIT","GYT","HANA","HANN",
        "HARN","HEALTH","HENG","HFT","HL","HMPRO","HPF","HPT","HTC","HTECH","HUMAN","HYDRO",
        "HYDROGEN","I2","ICC","ICHI","ICN","IDG","IFS","IHL","IIG","III","ILINK","ILM","IMH",
        "IMPACT","IND","INET","INETREIT","INGRS","INOX","INSET","INSURE","IP","IRC","IRCP",
        "IROYAL","IRPC","ISSARA","IT","ITC","ITD","ITEL","ITNS","ITTHI","IVF","IVL","J","JAK",
        "JAS","JCK","JCT","JDF","JMART","JMT","JPARK","JR","JSP","JTS","JUBILE","K","KAMART",
        "KASET","KBANK","KBS","KBSPIF","KC","KCAR","KCC","KCE","KCG","KCM","KDH","KGEN","KGI",
        "KIAT","KISS","KJL","KK","KKC","KKP","KLINIQ","KOOL","KPNREIT","KSL","KTB","KTBSTMR",
        "KTC","KTIS","KTMS","KUMWEL","KUN","KWC","KWI","KWM","KYE","L&E","LALIN","LANNA",
        "LDC","LEE","LEO"]

In [56]:
import pandas as pd

symbols_df = pd.DataFrame({
    "symbol": symbols
})

In [57]:
symbols_df.head()

   symbol
0     CRD
1  CREDIT
2     CSC
3     CSP
4     CSR

In [59]:
stocks_df = pd.read_sql(
    "SELECT stock_id, symbol FROM stocks;",
    engine
)

stocks_df

     stock_id   symbol
0         400      CRD
1         401   CREDIT
2         402      CSC
3           1       2S
4           2    3BBIF
..        ...      ...
393       194      CPT
394       195  CPTREIT
395       196      CPW
396       197    CRANE
397       198      CRC

[398 rows x 2 columns]

In [69]:
pd.read_sql("SELECT COUNT(*) FROM stocks;", engine)

   count
0    398

## ดึงชื่อบริษัทจริง 100% อัตโนมัติ”

In [72]:
symbols = ["CRD","CREDIT","CSC","CSP","CSR","CSS","CTARAF","CTW","CV","CWT","D","DCC","DCON","DDD",
        "DELTA","DEMCO","DEXON","DHOUSE","DIF","DIMET","DITTO","DMT","DOD","DOHOME","DPAINT",
        "DREIT","DRT","DTCENT","DTCI","DUSIT","DV8","EA","EASON","EAST","EASTW","ECF","EFORL",
        "EGATIF","EGCO","EKH","EMC","EMPIRE","EP","EPG","ERW","ESTAR","ETC","ETE","ETL","EURO",
        "EVER","F&D","FANCY","FE","FLOYD","FM","FMT","FN","FNS","FORTH","FPI","FPT","FSMART",
        "FSX","FTE","FTI","FTREIT","FUTURERT","FVC","GABLE","GAHREIT","GBX","GC","GCAP","GEL",
        "GENCO","GFC","GFPT","GGC","GJS","GLAND","GLOBAL","GLORY","GPI","GPSC","GRAMMY","GRAND",
        "GREEN","GROREIT","GSTEEL","GTB","GTV","GULF","GUNKUL","GVREIT","GYT","HANA","HANN",
        "HARN","HEALTH","HENG","HFT","HL","HMPRO","HPF","HPT","HTC","HTECH","HUMAN","HYDRO",
        "HYDROGEN","I2","ICC","ICHI","ICN","IDG","IFS","IHL","IIG","III","ILINK","ILM","IMH",
        "IMPACT","IND","INET","INETREIT","INGRS","INOX","INSET","INSURE","IP","IRC","IRCP",
        "IROYAL","IRPC","ISSARA","IT","ITC","ITD","ITEL","ITNS","ITTHI","IVF","IVL","J","JAK",
        "JAS","JCK","JCT","JDF","JMART","JMT","JPARK","JR","JSP","JTS","JUBILE","K","KAMART",
        "KASET","KBANK","KBS","KBSPIF","KC","KCAR","KCC","KCE","KCG","KCM","KDH","KGEN","KGI",
        "KIAT","KISS","KJL","KK","KKC","KKP","KLINIQ","KOOL","KPNREIT","KSL","KTB","KTBSTMR",
        "KTC","KTIS","KTMS","KUMWEL","KUN","KWC","KWI","KWM","KYE","L&E","LALIN","LANNA",
        "LDC","LEE","LEO"]

In [73]:
!pip install yfinance

Requirement already satisfied: yfinance in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.3.0)

In [74]:
import yfinance as yf
import pandas as pd

data = []

for sym in symbols:
    try:
        ticker = yf.Ticker(sym + ".BK")  # หุ้นไทยต้องเติม .BK
        info = ticker.info
        name = info.get("longName") or info.get("shortName") or sym
        
        data.append({
            "symbol": sym,
            "stock_name": name
        })
    except:
        data.append({
            "symbol": sym,
            "stock_name": sym
        })

df = pd.DataFrame(data)
df

     symbol                                         stock_name
0       CRD            Chiangmai Rimdoi Public Company Limited
1    CREDIT            Thai Credit Bank Public Company Limited
2       CSC                  Crown Seal Public Company Limited
3       CSP            CSP Steel Center Public Company Limited
4       CSR  City Sports and Recreation Public Company Limited
..      ...                                                ...
195   LALIN              Lalin Property Public Company Limited
196   LANNA             Lanna Resources Public Company Limited
197     LDC                  LDC Dental Public Company Limited
198     LEE               Lee Feed Mill Public Company Limited
199     LEO        Leo Global Logistics Public Company Limited

[200 rows x 2 columns]

In [75]:
df.head()

   symbol                                         stock_name
0     CRD            Chiangmai Rimdoi Public Company Limited
1  CREDIT            Thai Credit Bank Public Company Limited
2     CSC                  Crown Seal Public Company Limited
3     CSP            CSP Steel Center Public Company Limited
4     CSR  City Sports and Recreation Public Company Limited

In [76]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:password@localhost:5432/thai_stock_market"
)

In [77]:
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in df.iterrows():
        conn.execute(text("""
            INSERT INTO stocks (symbol, stock_name)
            VALUES (:symbol, :stock_name)
            ON CONFLICT (symbol)
            DO UPDATE SET
                stock_name = EXCLUDED.stock_name
        """), {
            "symbol": row["symbol"],
            "stock_name": row["stock_name"]
        })

print("✅ Upsert completed (no duplicate error)")

✅ Upsert completed (no duplicate error)

In [78]:
pd.read_sql("SELECT * FROM stocks ORDER BY symbol", engine)

,stock_id,symbol,stock_name,category_id,pe,pbv,eps,div_yield
0,1,2S,2S Metal Public Company Limited,20.0,None,None,None,None
1,2,3BBIF,3BB Internet Infrastructure Fund,20.0,None,None,None,None
2,3,88TH,88(Thailand) Public Company Limited,20.0,None,None,None,None
3,4,A,Areeya Property Public Company Limited,20.0,None,None,None,None
4,5,A5,Asset Five Group Public Company Limited,20.0,None,None,None,None
...,...,...,...,...,...,...,...,...
393,595,LALIN,Lalin Property Public Company Limited,NaN,None,None,None,None
394,596,LANNA,Lanna Resources Public Company Limited,NaN,None,None,None,None
395,597,LDC,LDC Dental Public Company Limited,NaN,None,None,None,None
396,598,LEE,Lee Feed Mill Public Company Limited,NaN,None,None,None,None
397,599,LEO,Leo Global Logistics Public Company Limited,NaN,None,None,None,None